name: Create Resource

on: [push]

env:
  L0_COMPANY_NAME: MyCleanTechComp
  DEFAULT_CLOUD_PROVIDER: GCP
  CLOUD_SECRETS: secretsGCP
  PULUMI_SECRETS: secretsPulumi
  GIT_LOCATION: Default
    
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          destination_repo: 'yabinboxes/pulumi-backend-MyCleanTechComp'
          destination_folder: 'test-dir'
          user_email: 'yabin.monroy.1@gmail.com'
          user_name: 'yabinboxes'
          commit_message: 'A custom message for the commit'
  
