name: Create Resource

on: [push]

env:
  L0_COMPANY_NAME: MyCleanTechComp
  DEFAULT_CLOUD_PROVIDER: GCP
  CLOUD_SECRETS: secretsGCP
  PULUMI_SECRETS: secretsPulumi
  GIT_LOCATION: Default
  BACKEND_NAME: pulumi-backend${{L0_COMPANY_NAME}}
    
jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create Pulumi Backend repo for company & configure
        run: |
          mkdir pulumi-backend-${L0_COMPANY_NAME}
          ls
          cd pulumi-backend-${L0_COMPANY_NAME}
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.GIT_TOKEN }}' \
          -d "{\"name\": \"${BACKEND_NAME}\", \"description\": \"This is a from an API call\"}" \
          https://api.github.com/user/repos
          
      #- name: Clone Pulumi Backend & write in local repo
      #  run: |
      #    npm install
      #    git clone https://github.com/yabinboxes/pulumi-backend
      #    ls
          
          
