name: Create Resource

on: [push]

env:
  L0_COMPANY_NAME: MyCleanTechComp
  DEFAULT_CLOUD_PROVIDER: GCP
  CLOUD_SECRETS: secretsGCP
  PULUMI_SECRETS: secretsPulumi
  GIT_LOCATION: Default
    
jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          persist-credentials: false
          fetch-depth: 0
      - name: Create Pulumi Backend repo for company & configure
        env: 
          BACKEND: pulumi-backend-${L0_COMPANY_NAME}
        run: |
          echo "------ clone repo pulumi-backend -----"
          git clone https://github.com/yabinboxes/pulumi-backend
          echo "------ create repo ------"
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.GIT_TOKEN }}' \
          -d "{\"name\": \"${{env.BACKEND}}\", \"description\": \"This is a from an API call\"}" \
          https://api.github.com/user/repos
          git clone https://github.com/yabinboxes/${{env.BACKEND}}
          echo "------ moving files ------"
          mv -v ./pulumi-backend/* ./${{env.BACKEND}}
          cd ${{env.BACKEND}}
          echo "------ config github -------"
          git config --global user.email "yabin.monroy.1@gmail.com"
          git config --global user.name "yabinboxes"
          git add -A
          git commit -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
          
      #- name: Clone Pulumi Backend & write in local repo
      #  run: |
      #    npm install
      #    git clone https://github.com/yabinboxes/pulumi-backend
      #    ls
          
          
