name: Create Resource

on: [push]

env:
  L0_COMPANY_NAME: MyCleanTechComp
  DEFAULT_CLOUD_PROVIDER: GCP
  CLOUD_SECRETS: secretsGCP
  PULUMI_SECRETS: secretsPulumi
  GIT_LOCATION: Default
    
jobs:
  copy-file:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Create enterprise pulumi-backend repository
        run: |
          echo "------ clone repo pulumi-backend -----"
          git clone https://github.com/yabinboxes/pulumi-backend
          echo "------ create repo ------"
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}' \
          -d "{\"name\": \"pulumi-backend-MyCleanTechComp\", \"auto_init\": \"true\", \"description\": \"This is a from an API call\"}" \
          https://api.github.com/user/repos
          echo "------ list all ------"
          ls

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: pulumi-backend/.
          destination_repo: 'yabinboxes/pulumi-backend-MyCleanTechComp'
          destination_folder: 'test-dir'
          user_email: 'yabin.monroy.1@gmail.com'
          user_name: 'yabinboxes'
          commit_message: 'A custom message for the commit'
          
      - name: Auto deploy backend
        run: |
          cd pulumi-backend
          npm ci
          npm run dev > /dev/null 2>&1 &
          sleep 2s
          curl -X GET 'http://localhost:5000/autodeploy' -H 'accept: application/json'
          
      - name: Update urls files
        run: |
          echo "----- update urls -----"
          echo "new urls for app" >> pulumi-backend/urls/app-url
          echo "new urls for database" >> pulumi-backend/urls/db-url
          
