name: Create Resource

on: [push]

env:
  L0_COMPANY_NAME: MyCleanTechComp
  DEFAULT_CLOUD_PROVIDER: GCP
  CLOUD_SECRETS: secretsGCP
  PULUMI_SECRETS: secretsPulumi
  GIT_LOCATION: Default
    
jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create Pulumi Backend repo for company & configure
        env: 
          BACKEND: pulumi-backend-${L0_COMPANY_NAME}
        run: |
          git clone https://github.com/yabinboxes/pulumi-backend
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.GIT_TOKEN }}' \
          -d "{\"name\": \"${{env.BACKEND}}\", \"description\": \"This is a from an API call\"}" \
          https://api.github.com/user/repos
          echo "------ cloning code ------"
          git clone https://github.com/yabinboxes/${{env.BACKEND}}
          ls
          echo "------ moving files ------"
          mv -v ./pulumi-backend/* ./${{env.BACKEND}}
          cd ${{env.BACKEND}}
          echo "------ display content ------"
          ls
          git add -A
          git commit -m "first commit"
          git push -u origin main
          
          
      #- name: Clone Pulumi Backend & write in local repo
      #  run: |
      #    npm install
      #    git clone https://github.com/yabinboxes/pulumi-backend
      #    ls
          
          
